### ISSUE TITLE
mksrcinfo fails to work on PKGBUILD using makepkg's error, msg, and msg2 functions

### ISSUE THREAD

**Issue by phillid** [falconindy/pkgbuild-introspection#24]
I have a PKGBUILD which uses `msg`, `msg2` and `error` to make error and info messages look nicer. Of course, `mksrcinfo` doesn't define these functions, so running `mksrcinfo` on this PKGBUILD causes the following error:

    ~/somedir/PKGBUILD: line 28: error: command not found

Commenting the line out causes the script to complete successfully.

Of course, note that `makepkg --source` builds `.SRCINFO` just fine.

**Comment by falconindy** [comment]
Does this mean you're writing messages from somewhere outside of a packaging function? Why would you do that?

**Comment by phillid** [comment]
This is the same PKGBUILD in question in #25 and as such, this issue isn't relevant anymore. Thanks for your time.
