### ISSUE TITLE
Wrong permissions of .SRCINFO

### ISSUE THREAD

**Issue by dracorp** [falconindy/pkgbuild-introspection#28]
Hello
I have installed pkgbuild-introspection-git-6.4.ga135f86-1 and mkaurball creates .SRCINFO with wrong permission 0664.
Could you fix it?

**Comment by falconindy** [comment]
No, because I don't know what needs fixing given your sparse bug report. If you're using pacman 4.2.0, then the problem likely isn't in mkaurball, it's in makepkg. If you're using an older version of pacman, what is your umask set to?

**Comment by dracorp** [comment]
My mistake, you were right and I'm using pacman 0.4.2.
So I'll check makepkg and bugtracker.
Best regards.
