### ISSUE TITLE
mkaurball should fix permissions

### ISSUE THREAD

**Issue by darkfeline** [falconindy/pkgbuild-introspection#30]
`mkaurball` should fix permissions for files automatically.  I often get errors uploading packages to the AUR with the message "All files must have permissions 644 or 755".  Since 'mkaurball' is the standard tool for making source packages for the AUR, it should check for this and fix automatically.

**Comment by falconindy** [comment]
Because of the "or" in that sentence, mkaurball can only guess at what the perms should be changed to. How about the user just gets this right instead?

Also, makepkg fills the role these days, not mkaurball.

**Comment by darkfeline** [comment]
Sorry, last I checked mkaurball was recommended for making source packages.

There is no ambiguity regarding 644 or 755.  Files are 644, directories are 755.

**Comment by falconindy** [comment]
That's a narrow-minded view of the reality that is the AUR. Many PKGBUILDs package scripts as 755 (launchers, utilities, etc) and depend on these being preserved by something like cp(1) rather than a less brittle 'install -m755' or whatever. This isn't ideal, but it's also not really wrong.

**Comment by darkfeline** [comment]
Such packages would benefit from getting fixed going forward if they are ever updated, similar to old packages missing package()/build() functions that will need to be fixed to be re-submitted.  It's better for bad packages to break loudly rather than be implicitly allowed.

Anyway, moot point since makepkg is the current tool, sorry for bothering you.

**Comment by falconindy** [comment]
It's a difference in philosophy. I'm not interested in policing PKGBUILDs, just providing a mechanism to make source tarballs. AUR rules can change, and I don't want to maintain some sort of "linting" mechanism which might float out of sync with the AUR's rules.

If makepkg changes, I'll make changes here. But, I see no reason to do so.
