### ISSUE TITLE
timestamp uneccesarily dirties package repository

### ISSUE THREAD

**Issue by dffischer** [falconindy/pkgbuild-introspection#32]
In my daily use of `mksrcinfo`, I find commit f4ae8e8375392cb1df4b525d338c1642202787b9 to be quite impractical.

I often forget to update the `.SRCINFO` when I made changes to the `PKGBUILD`, so I often automate `mksrcinfo` execution. A git hook can easily invoke it before every commit. With a timestamp in every `.SRCINFO`, the file is guaranteed to change whenever `mksrcinfo` is run. This introduces unnecessary changes into the repository, as it is possible for the `PKGBUILD` or other files in the package repository to change without affecting the contents of `.SRCINFO`.

I am aware that I could manually filter out the line, but would prefer a command-line switch to turn off the timestamp to begin with. An even better possibility would be to use the modification time of the PKGBUILD in place of the time `mksrcinfo` was run.

I see that the timestamp was introduced to mirror the behaviour of `makepkg`. I am unsure whether this issue does belong here or should be discussed on the pacman-dev mailinglist, so feel free to redirect my request, if you think so.

**Comment by falconindy** [comment]
If you dislike this behavior, please bring it up with pacman-dev. I'm trying to stay as close to pacman upstream as possible.

**Comment by lucaswerkmeister** [comment]
Late update: the timestamp seems to be gone with 7888e4ca6253f40ce2c656ef0eedd57910e4b974.
