### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Morganamilo** [falconindy/pkgbuild-introspection#35]
For some reason many AUR packages still use `mksrcinfo` for .SRCINFO generation. The current v8 of `pkgbuild-introspection` still uses its own srcinfo generation code. Where in master this is pretty much just forwarded to `makepkg` (and that change was made over 3 years ago).

This is pretty annoying as the current release version of mksrcinfo omits certain fields such as `validpgpkeys` were makepkg (and therefore the current master) prints them.

**Comment by falconindy** [comment]
You can blame [this AUR package](https://aur.archlinux.org/packages/pkgbuild-introspection) for being reanimated.

Grumble. Sure, I'll tag a new release.
